# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='消费子类型')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='消费类型')),
            ],
        ),
        migrations.AddField(
            model_name='consumptionsubtype',
            name='higher_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptionsubtype_higher_type', to='bankcard.ConsumptionType', verbose_name='父类型'),
        ),
    ]
