# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='交易金额')),
                ('type', models.BooleanField(default=True, verbose_name='交易类型')),
                ('transaction_datetime', models.DateTimeField(blank=True, null=True, verbose_name='交易时间')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('consumption_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionlog_consumption_type', to='bankcard.ConsumptionSubType', verbose_name='消费类型')),
            ],
        ),
    ]
