# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankcard', '0002_transactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='银行名称')),
                ('type', models.CharField(choices=[('debit_card', '借记卡'), ('credit_card', '信用卡')], max_length=100, unique=True, verbose_name='类型名称')),
                ('valid_until', models.DateTimeField(verbose_name='有效期至')),
                ('bill_day', models.DateTimeField(verbose_name='账单日')),
                ('repay_day', models.DateTimeField(verbose_name='还款日')),
                ('annual_fee', models.FloatField(verbose_name='年费/元')),
                ('free', models.BooleanField(verbose_name='是否可免费')),
                ('free_condition', models.CharField(blank=True, max_length=100, null=True, verbose_name='免费条件')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bankcardinfo_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('mender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bankcardinfo_mender', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
                ('transaction_log', models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bankcardinfo_creator', to='bankcard.TransactionLog', verbose_name='交易记录')),
            ],
        ),
    ]
