# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcard', '0003_bankcardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcardinfo',
            name='card_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='银行卡号'),
        ),
    ]
