# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankcard', '0005_auto_20181107_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
            ],
        ),
        migrations.AlterField(
            model_name='bankcardinfo',
            name='transaction_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bankcardinfo_creator', to='bankcard.TransactionLog', verbose_name='交易记录'),
        ),
        migrations.AlterField(
            model_name='bankcardinfo',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bankcardinfo_creator', to='bankcard.BankCardType', verbose_name='交易记录'),
        ),
    ]
