# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankcard', '0007_auto_20181109_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcardinfo',
            old_name='free',
            new_name='is_free',
        ),
        migrations.AlterField(
            model_name='bankcardinfo',
            name='bankcard_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bankcardinfo_bankcard_type', to='bankcard.BankCardType', verbose_name='银行卡类型'),
        ),
    ]
