# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankcard', '0008_auto_20181109_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcardinfo',
            name='annual_fee',
            field=models.FloatField(blank=True, null=True, verbose_name='年费/元'),
        ),
        migrations.AlterField(
            model_name='bankcardinfo',
            name='bill_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='账单日'),
        ),
        migrations.AlterField(
            model_name='bankcardinfo',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='是否可免费'),
        ),
        migrations.AlterField(
            model_name='bankcardinfo',
            name='repay_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='还款日'),
        ),
        migrations.AlterField(
            model_name='bankcardinfo',
            name='transaction_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bankcardinfo_transaction_log', to='bankcard.TransactionLog', verbose_name='交易记录'),
        ),
        migrations.AlterField(
            model_name='bankcardinfo',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有效期至'),
        ),
    ]
