# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcard', '0009_auto_20181109_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcardinfo',
            name='bill_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='账单日'),
        ),
        migrations.AlterField(
            model_name='bankcardinfo',
            name='repay_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='还款日'),
        ),
    ]
