# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankcard', '0010_auto_20181109_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcardinfo',
            name='transaction_log',
        ),
    ]
