# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankcard', '0011_remove_bankcardinfo_transaction_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcardinfo',
            name='bankcard_num',
            field=models.CharField(max_length=100, unique=True, verbose_name='银行卡号'),
        ),
    ]
