# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='基金名称')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total', models.FloatField(verbose_name='交易金额')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fundinfo_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('mender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fundinfo_mender', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='交易金额')),
                ('sha', models.FloatField(blank=True, null=True, verbose_name='上证指数')),
                ('nav', models.FloatField(blank=True, null=True, verbose_name='单位净值')),
                ('type', models.BooleanField(choices=[('buy', '买入'), ('sell', '卖出')], default='buy', verbose_name='交易类型')),
                ('transaction_datetime', models.DateTimeField(verbose_name='交易时间')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactionlog_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('mender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactionlog_mender', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
        ),
        migrations.AddField(
            model_name='fundinfo',
            name='transaction_log',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fundinfo_creator', to='fund.TransactionLog', verbose_name='交易记录'),
        ),
    ]
