# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authoritycontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_auth', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='用例权限')),
                ('sys_auth', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='平台权限')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
