# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SayingEveryday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='出处')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sayingeveryday_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('mender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sayingeveryday_mender', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
        ),
    ]
