# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FictionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='小说名称')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('file_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件地址')),
                ('status', models.BooleanField(choices=[('ready', '未开始'), ('finding', '搜索中'), ('downing', '下载中'), ('done', '已下载'), ('not_found', '未找到')], default='ready', verbose_name='交易类型')),
                ('dialysis_pic', models.CharField(blank=True, max_length=100, null=True, verbose_name='透析图地址')),
                ('source', models.CharField(max_length=100, verbose_name='资源来源')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('total', models.FloatField(verbose_name='交易金额')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fictioninfo_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('mender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fictioninfo_mender', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
        ),
        migrations.CreateModel(
            name='SourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('site_url', models.CharField(max_length=100, verbose_name='网址')),
                ('search_script', models.CharField(blank=True, max_length=100, null=True, verbose_name='搜索脚本地址')),
                ('down_script', models.CharField(blank=True, max_length=100, null=True, verbose_name='下载脚本地址')),
                ('status', models.BooleanField(choices=[('ready', '待录入'), ('able', '可用'), ('disable', '失效')], default='ready', verbose_name='交易类型')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功下载资源次数')),
                ('success_rate', models.FloatField(default=0, verbose_name='成功率')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sourceinfo_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('mender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sourceinfo_mender', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='标签')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('mender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_mender', to=settings.AUTH_USER_MODEL, verbose_name='修改者')),
            ],
        ),
        migrations.AddField(
            model_name='fictioninfo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='fiction.Tag', verbose_name='标签'),
        ),
    ]
