# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FictionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
            ],
        ),
        migrations.AddField(
            model_name='fictioninfo',
            name='fiction_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fictioninfo_fiction_type', to='fiction.FictionType', verbose_name='小说类型'),
        ),
    ]
