# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0002_auto_20181113_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='mender',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='update_datetime',
        ),
    ]
