# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0003_auto_20181113_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FictionType',
            new_name='Type',
        ),
    ]
