# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0004_auto_20181113_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='作者名')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='状态名称')),
            ],
        ),
        migrations.AlterField(
            model_name='fictioninfo',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fictioninfo_author', to='fiction.Author', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='fictioninfo',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fictioninfo_fiction_status', to='fiction.Status', verbose_name='小说状态'),
        ),
    ]
