# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0009_remove_fictioninfo_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='状态名称')),
            ],
        ),
        migrations.AlterField(
            model_name='sourceinfo',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sourceinfo_source_status', to='fiction.SourceStatus', verbose_name='资源状态'),
        ),
    ]
