# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0010_auto_20181114_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceinfo',
            old_name='down_script',
            new_name='download_script',
        ),
    ]
