# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiction', '0011_auto_20181117_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fictioninfo',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fictioninfo_source', to='fiction.SourceInfo', verbose_name='资源来源'),
        ),
    ]
