# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_auto_20181113_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_language', to='reading.Language', verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='readingplan_plan_status', to='reading.Status', verbose_name='计划状态'),
        ),
    ]
